// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiqJA6CqR4T57gW-bOTMDE2zSYPwbVfhk',
    appId: '1:886662903727:web:70db73141e1e9530fe615a',
    messagingSenderId: '886662903727',
    projectId: 'instagram-clone-3bf3a',
    authDomain: 'instagram-clone-3bf3a.firebaseapp.com',
    storageBucket: 'instagram-clone-3bf3a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMv0Q_Ynq1Gmy1cQfZrZ0T3N4GhWqe0a8',
    appId: '1:886662903727:android:320a89d0e44ae3b6fe615a',
    messagingSenderId: '886662903727',
    projectId: 'instagram-clone-3bf3a',
    storageBucket: 'instagram-clone-3bf3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGeX3VCY_GYEDhgbDv__MdyYR1Svxa27M',
    appId: '1:886662903727:ios:6293e8210aa2764afe615a',
    messagingSenderId: '886662903727',
    projectId: 'instagram-clone-3bf3a',
    storageBucket: 'instagram-clone-3bf3a.appspot.com',
    iosClientId: '886662903727-am9oolf84ama39j33bhaeqj5mdisci4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGeX3VCY_GYEDhgbDv__MdyYR1Svxa27M',
    appId: '1:886662903727:ios:6293e8210aa2764afe615a',
    messagingSenderId: '886662903727',
    projectId: 'instagram-clone-3bf3a',
    storageBucket: 'instagram-clone-3bf3a.appspot.com',
    iosClientId: '886662903727-am9oolf84ama39j33bhaeqj5mdisci4j.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
