// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXpfRdNlo48Xtb5VcVvXO6yhiK7dUdUF8',
    appId: '1:338559345318:web:f882ece860e15cdf0dca67',
    messagingSenderId: '338559345318',
    projectId: 'whatsapp-clone-6d9e2',
    authDomain: 'whatsapp-clone-6d9e2.firebaseapp.com',
    storageBucket: 'whatsapp-clone-6d9e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTCFm4YApUYR460qCNhJyTJgYOc6gsPi8',
    appId: '1:338559345318:android:cde52ca1759d5acb0dca67',
    messagingSenderId: '338559345318',
    projectId: 'whatsapp-clone-6d9e2',
    storageBucket: 'whatsapp-clone-6d9e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQUiuZg3mBoSWjWDx4nQK3EvTDCiMnhDE',
    appId: '1:338559345318:ios:1b83917c3cddd7930dca67',
    messagingSenderId: '338559345318',
    projectId: 'whatsapp-clone-6d9e2',
    storageBucket: 'whatsapp-clone-6d9e2.appspot.com',
    iosClientId: '338559345318-0m3jk7r2pncuunatnpr5pqep7tp509l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappUi',
  );
}
